import random

def generate_caption(video_path):
    # 100 SEO-optimized general captions
    base_captions = [
        "Watch till the end for something amazing! ✨",
        "You won't believe this moment 😲",
        "This will make your day better 🌟",
        "Ultimate content you need to see now 🔥",
        "Don't miss this incredible video! 🎥",
        "Life-changing moment captured on camera 😎",
        "The most satisfying video you'll see today 💯",
        "Trending now! Join the hype 😍",
        "Your daily dose of entertainment 🎉",
        "Amazing skills you have to watch 👏",
        "Unbelievable, yet true! 😲",
        "Get ready to be inspired 💡",
        "This will blow your mind 💥",
        "Fun, funny, and totally worth watching 😂",
        "Top trending content right here 🔥",
        "Prepare to be amazed 🌈",
        "This deserves a double tap ❤️",
        "The content everyone is talking about 🗣️",
        "You'll want to share this with friends 📲",
        "Epic moments caught on camera 🎬",
        "Incredible, unbelievable, unforgettable! 😱",
        "A must-watch video for today 🌟",
        "The most satisfying content you'll see 💯",
        "Life, captured beautifully 📸",
        "You won’t see this anywhere else 😎",
        "Viral content you can’t miss 🔥",
        "This is pure entertainment 😂",
        "Mind-blowing content just for you 🤯",
        "Discover something new today 🧐",
        "This video is everything you need 😍",
        "Best content you’ll watch this week 💥",
        "Amazing talent on full display 👏",
        "So satisfying, you have to watch till the end ✅",
        "Trending content you’ll love 🔝",
        "This video is pure gold 🏆",
        "Get ready to be amazed by this 🎉",
        "This content is absolutely insane 😱",
        "You need to see this now 🔥",
        "Fun moments to brighten your day 🌈",
        "Epic content coming your way 🚀",
        "You won’t believe what happens next 😲",
        "Best moments captured for you 📸",
        "This video is guaranteed to wow you 💥",
        "Ultimate entertainment for everyone 🎬",
        "Watch, laugh, and enjoy 😂",
        "Top trending moments you must see 🔝",
        "The most incredible content online 🌟",
        "Prepare yourself for pure entertainment 🤩",
        "This video is too good to miss 💯",
        "Amazing moments captured perfectly 🎥",
        "You will love this content ❤️",
        "This is what everyone is talking about 🗣️",
        "Viral content you can’t stop watching 🔥",
        "Incredible, entertaining, and epic 😎",
        "Watch this for ultimate fun 🎉",
        "The content you need in your feed 💡",
        "So satisfying, you have to see it 🧐",
        "The ultimate video experience 🌈",
        "You won’t believe your eyes 👀",
        "This video is trending worldwide 🌍",
        "Must-watch content for today 🔥",
        "Epic moments that make you smile 😊",
        "Discover amazing videos every day 📲",
        "This will blow your mind 🤯",
        "Incredible talent on display 👏",
        "The most entertaining video today 💥",
        "Watch, enjoy, and share 😍",
        "Top trending content for your feed 🔝",
        "This video is pure entertainment 😂",
        "Fun, exciting, and worth watching 🎬",
        "Prepare for something incredible 🌟",
        "The content everyone loves 💯",
        "Amazing moments captured perfectly 📸",
        "You need to watch this video now 🔥",
        "Epic content coming straight to you 🚀",
        "This is everything you need today 🌈",
        "Watch till the end for a surprise 🎉",
        "Top trending video you can’t miss 🔝",
        "Pure entertainment for everyone 😂",
        "You’ll be amazed by this content 😲",
        "Fun and exciting moments captured perfectly 🎥",
        "This video is going viral worldwide 🌍",
        "The ultimate video for your feed 💡",
        "Unbelievable moments captured on camera 😱",
        "Epic content that will wow you 🤩",
        "Watch, like, and share this amazing video ❤️",
        "The most entertaining content today 💥",
        "You won’t stop watching this 😂",
        "Trending now! Don’t miss out 🔥",
        "Fun, engaging, and absolutely epic 🎬",
        "The best moments captured for you 🌟",
        "Prepare to be entertained all day 😎",
        "Amazing content for everyone 📲",
        "Viral video you can’t miss 🔝",
        "This video is pure fun and excitement 😍",
        "Epic moments you have to see 💯",
        "Watch, enjoy, and be amazed 🎉",
        "Top trending moments that make your day 🌈",
        "This video is too good to ignore 💥",
        "Fun, entertaining, and totally worth watching 😂",
        "Prepare for epic entertainment 🌟",
        "Amazing moments that will wow you 😲",
        "The ultimate video experience for everyone 🎬",
        "Trending content that will make you smile 😊",
        "Watch this video and brighten your day 🌈",
        "Pure fun and epic moments captured 💯",
        "The best content you’ll see today 🔥",
        "Unbelievable and satisfying content 🤩",
        "Epic video moments for your feed 📲",
        "Watch, laugh, and enjoy this amazing video 🎉",
        "Top trending video that everyone loves ❤️"
    ]

    # SEO optimized hashtags for general videos
    hashtags = (
        "#Trending #ViralVideos #Entertainment #FunnyVideos #MustWatch "
        "#Explore #DailyContent #VideoOfTheDay #InstaVideo #ReelsDaily "
        "#ContentCreator #VideoTrends #ViralNow #WatchThis #TopContent"
    )

    return f"{random.choice(base_captions)}\n\n{hashtags}"
